import os
import sys
import pandas as pd
from sqlalchemy import create_engine

# =====================================================================
# 1. CONFIGURATION & DATABASE CONNECTION
# =====================================================================
# The file that was generated by your AI agent
ENRICHED_FILE = "Leads_PA_BA_SE_GO_v3.xlsx"

# 🔴 INSERT YOUR REAL NEON.TECH POSTGRESQL STRING HERE
# (This must be the EXACT same string you put in Vercel's Environment Variables)
DATABASE_URL = "postgresql://neondb_owner:npg_LROEPwgm05jB@ep-jolly-sky-amgsdm53.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require"

# The name of the table in your CRM database (Usually 'leads', 'Lead', or 'customers')
DB_TABLE_NAME = "leads"

if "user:password" in DATABASE_URL:
    sys.exit("🚨 ERROR: Please update line 14 with your real Neon.tech database URL.")

print("🔌 Connecting to the live PostgreSQL Database...")
engine = create_engine(DATABASE_URL)

# =====================================================================
# 2. FILTERING & INGESTION PIPELINE
# =====================================================================
def upload_and_filter_leads():
    if not os.path.exists(ENRICHED_FILE):
        sys.exit(f"❌ Error: File '{ENRICHED_FILE}' not found. Keep it in the same folder as this script.")

    print(f"📁 Reading enriched data from: {ENRICHED_FILE}")
    xls_data = pd.read_excel(ENRICHED_FILE, sheet_name=None)
    
    total_injected = 0

    for sheet_name, df in xls_data.items():
        print(f"\n⚙️ Processing Sheet: {sheet_name} (Initial rows: {len(df)})")
        
        # Updated to check for the new column name
        if "Nome_Empresa" not in df.columns:
            print("   [!] Skipping sheet: No enriched columns found.")
            continue

        # -----------------------------------------------------------------
        # 🎯 APPLYING INVESTOR-GRADE QUALITY FILTERS
        # -----------------------------------------------------------------
        # Filter 1: Remove "Ghosts" (Companies the AI couldn't find) using new column names
        df_filtered = df[
            (df["Nome_Empresa"].notna()) & 
            (df["Nome_Empresa"].astype(str).str.strip() != "") &
            (df["Nome_Empresa"] != "Não encontrado")
        ]
        
        # Filter 2: Only keep highly actionable leads (Must have Email OR LinkedIn)
        df_filtered = df_filtered[
            (df_filtered["Email_Estimado"] != "Não encontrado") | 
            (df_filtered["LinkedIn"] != "Não encontrado")
        ]

        leads_to_upload = len(df_filtered)
        print(f"   => After strict filtering, {leads_to_upload} highly qualified leads remain.")

        if leads_to_upload == 0:
            continue

        # -----------------------------------------------------------------
        # 🗺️ DATA MAPPING TO MATCH CRM SCHEMA
        # -----------------------------------------------------------------
        # IMPORTANT: Updated to map the new Excel column names to your CRM schema
        crm_dataframe = pd.DataFrame({
            "company_name": df_filtered["Nome_Empresa"],
            "domain": df_filtered["Dominio"],
            "decision_maker_name": df_filtered["Decisor_Nome"],
            "decision_maker_role": df_filtered["Decisor_Cargo"],
            "email": df_filtered["Email_Estimado"],
            "linkedin": df_filtered["LinkedIn"],
            "city": df_filtered["Municipio"],
            "status": "NEW", # Default pipeline stage in the CRM
            "created_at": pd.Timestamp.now()
        })

        # -----------------------------------------------------------------
        # 💾 INJECT INTO NEON.TECH
        # -----------------------------------------------------------------
        print(f"   [💾] Injecting {leads_to_upload} leads into the live CRM table '{DB_TABLE_NAME}'...")
        try:
            # if_exists='append' adds to the database without deleting existing data
            crm_dataframe.to_sql(DB_TABLE_NAME, engine, if_exists='append', index=False)
            total_injected += leads_to_upload
            print("   ✅ Injection successful!")
        except Exception as e:
            print(f"   ❌ Database Error: {e}")
            print("   (Hint: Check if 'DB_TABLE_NAME' and the column names match your Drizzle schema)")

    print(f"\n🚀 MVP COMPLETE! Successfully injected {total_injected} qualified leads into the live CRM.")

if __name__ == "__main__":
    upload_and_filter_leads()